src/network/protocols/ranking.hpp: add missing `<stdint.h>` include
Without the chnage the build fails on upcoming `gcc-15` as:

    /build/source/src/network/protocols/ranking.hpp:31:5: error: 'uint32_t' does not name a type
       31 |     uint32_t online_id;
          |     ^~~~~~~~